<?php

namespace Cacko\Yii2\Widgets\FullScreen;

use yii\base\Widget;
use yii\helpers\Json;

trait RegisterWidgetTrait
{

    public static function registerWidget(Widget $widget, $options = []): \yii\web\AssetBundle
    {

        $view = $widget->view;
        $widgetId = $widget->id;
        $options = Json::encode($options);

        $assetName = (new \ReflectionClass(get_called_class()))->getShortName();
        $pluginName = ucfirst(str_replace('Asset', '', $assetName));

        $bundle = static::register($view); // TODO: Change the autogenerated stub
        $view->registerJs(sprintf("$('#%s').widget%s(%s);", $widgetId, $pluginName, $options));

        return $bundle;
    }
}
